../src/000-common.core/VHDL_HELP_FUNC_PKG.vhd
../src/a.b-DATAPATH.core/000-ALU_PKG.vhd
../src/000-common.core/000-DLX_PKG.vhd
../src/000-common.core/001-DLX_ISA_ENC_PKG.vhd
../src/000-common.core/002-REG_PIPO.vhd
../src/a.e-HU.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/000-common.core/fa.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/000-common.core/rca.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/carry_generator/CARRY_GENERATOR_PKG.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/carry_generator/GG.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/carry_generator/GP.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/carry_generator/PG_PRIM.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/carry_generator/CARRY_GENERATOR.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/sum_generator/CSB.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4-ADDER.core/sum_generator/SUM_GENERATOR.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.a-P4_ADDER.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.b-T2_SHIFTER.core/coarse_shift.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.b-T2_SHIFTER.core/fine_shift.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.b-T2_SHIFTER.core/mask_gen.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.b-T2_SHIFTER.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.core/a.b.b.c-T2_LOGIC.vhd
../src/a.b-DATAPATH.core/a.b.b-ALU.vhd
../src/a.b-DATAPATH.core/a.b.a-RF.vhd
../src/a.b-DATAPATH.vhd
../src/a.a-CU.vhd
../src/c-DMEM.vhd
../src/b-IMEM.vhd
../src/a-CPU.vhd

# Testbench stuff
../sim/CLKGEN.vhd
../sim/tb_IMEM.vhd
../sim/tb_T2_SHIFTER.vhd
../sim/tb_CU.vhd
../sim/tb_DATAPATH.vhd
../sim/tb_CPU.vhd
../sim/tb_T2_LOGIC.vhd
