#../src/00-common.core/001-CU_PKG.vhd
../src/00-common.core/VHDL_HELP_FUNC_PKG.vhd
../src/a.b-DATAPATH.core/00-ALU_PKG.vhd
../src/00-common.core/000-DLX_PKG.vhd
../src/00-common.core/001-DLX_ISA_ENC_PKG.vhd
../src/00-common.core/002-REG_PIPO.vhd
../src/a.c-IMEM.vhd
../src/a.d-DMEM.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/000-common.core/fa.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/000-common.core/rca.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/carry_generator/CARRY_GENERATOR_PKG.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/carry_generator/GG.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/carry_generator/GP.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/carry_generator/PG_PRIM.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/carry_generator/CARRY_GENERATOR.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/sum_generator/LFSR.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/sum_generator/CSB.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-p4-adder.core/sum_generator/SUM_GENERATOR.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.a-P4_ADDER.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/d.i.o.c-T2_SHIFTER.core/d.i.o.c-coarse_shift.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/d.i.o.c-T2_SHIFTER.core/d.i.o.c-fine_shift.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/d.i.o.c-T2_SHIFTER.core/d.i.o.c-mask_gen.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/d.i.o.c-T2_SHIFTER.vhd
#../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.b-booth-mul.core/boothenc.vhd
#../src/a.b-DATAPATH.core/a.b.a-ALU.core/a.b.a.b-boothmul.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.core/d.i.o.c-T2_LOGIC.vhd
../src/a.b-DATAPATH.core/a.b.a-ALU.vhd
#../src/a.b-DATAPATH.core/RF/ADDR_DEC.vhd
#../src/a.b-DATAPATH.core/RF/RF_PKG.vhd
#../src/a.b-DATAPATH.core/RF/WRF.vhd
#../src/a.b-DATAPATH.core/RF/WRF_CU.vhd
#../src/a.b-DATAPATH.core/RF/RF.vhd
../src/a.b-DATAPATH.core/a.b.b-RF.vhd
../src/a.b-DATAPATH.vhd
../src/a.a-CU.vhd
../src/a-CPU.vhd

# Testbench stuff
../sim/CLKGEN.vhd
../sim/tb_CU.vhd
../sim/tb_CPU.vhd
../sim/tb_DATAPATH.vhd
